
# This file is automatically generated, you probably don't want to edit this

barplotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            columns = NULL,
            facet = NULL,
            ignoreNA = TRUE,
            horizontal = FALSE,
            rotateLabels = FALSE,
            showLabels = TRUE,
            order = "none",
            yaxis1var = "count",
            singleColor = TRUE,
            position = "dodge",
            colorPalette = "jmv",
            borderColor = "none",
            textColor = "auto",
            accuracy = "0.1",
            plotWidth = 0,
            plotHeight = 0,
            facetBy = "column",
            facetNumber = 1,
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5",
            yAxisLabelFontSize = 12,
            yAxisLabelRotation = 0,
            yAxisRangeType = "auto",
            yAxisRangeMin = 0,
            yAxisRangeMax = 10,
            xAxisLabelFontSize = 12,
            xAxisLabelRotation = 0,
            xAxisRangeType = "auto",
            xAxisRangeMin = 0,
            xAxisRangeMax = 10, ...) {

            super$initialize(
                package="vijPlots",
                name="barplot",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..columns <- jmvcore::OptionVariable$new(
                "columns",
                columns,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..facet <- jmvcore::OptionVariable$new(
                "facet",
                facet,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..ignoreNA <- jmvcore::OptionBool$new(
                "ignoreNA",
                ignoreNA,
                default=TRUE)
            private$..horizontal <- jmvcore::OptionBool$new(
                "horizontal",
                horizontal,
                default=FALSE)
            private$..rotateLabels <- jmvcore::OptionBool$new(
                "rotateLabels",
                rotateLabels,
                default=FALSE)
            private$..showLabels <- jmvcore::OptionBool$new(
                "showLabels",
                showLabels,
                default=TRUE)
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="none")
            private$..yaxis1var <- jmvcore::OptionList$new(
                "yaxis1var",
                yaxis1var,
                options=list(
                    "count",
                    "percent"),
                default="count")
            private$..singleColor <- jmvcore::OptionBool$new(
                "singleColor",
                singleColor,
                default=TRUE)
            private$..position <- jmvcore::OptionList$new(
                "position",
                position,
                options=list(
                    "dodge",
                    "dodge2",
                    "stack",
                    "fill"),
                default="dodge")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12"),
                default="jmv")
            private$..borderColor <- jmvcore::OptionList$new(
                "borderColor",
                borderColor,
                options=list(
                    "none",
                    "black",
                    "white",
                    "gray"),
                default="none")
            private$..textColor <- jmvcore::OptionList$new(
                "textColor",
                textColor,
                options=list(
                    "black",
                    "white",
                    "auto"),
                default="auto")
            private$..accuracy <- jmvcore::OptionList$new(
                "accuracy",
                accuracy,
                options=list(
                    "1",
                    "0.1",
                    "0.01"),
                default="0.1")
            private$..plotWidth <- jmvcore::OptionNumber$new(
                "plotWidth",
                plotWidth,
                min=0,
                max=1000,
                default=0)
            private$..plotHeight <- jmvcore::OptionNumber$new(
                "plotHeight",
                plotHeight,
                min=0,
                max=1600,
                default=0)
            private$..facetBy <- jmvcore::OptionList$new(
                "facetBy",
                facetBy,
                options=list(
                    "row",
                    "column"),
                default="column")
            private$..facetNumber <- jmvcore::OptionNumber$new(
                "facetNumber",
                facetNumber,
                min=1,
                max=10,
                default=1)
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")
            private$..yAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "yAxisLabelFontSize",
                yAxisLabelFontSize,
                default=12)
            private$..yAxisLabelRotation <- jmvcore::OptionNumber$new(
                "yAxisLabelRotation",
                yAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..yAxisRangeType <- jmvcore::OptionList$new(
                "yAxisRangeType",
                yAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..yAxisRangeMin <- jmvcore::OptionNumber$new(
                "yAxisRangeMin",
                yAxisRangeMin,
                default=0)
            private$..yAxisRangeMax <- jmvcore::OptionNumber$new(
                "yAxisRangeMax",
                yAxisRangeMax,
                default=10)
            private$..xAxisLabelFontSize <- jmvcore::OptionNumber$new(
                "xAxisLabelFontSize",
                xAxisLabelFontSize,
                default=12)
            private$..xAxisLabelRotation <- jmvcore::OptionNumber$new(
                "xAxisLabelRotation",
                xAxisLabelRotation,
                default=0,
                min=0,
                max=360)
            private$..xAxisRangeType <- jmvcore::OptionList$new(
                "xAxisRangeType",
                xAxisRangeType,
                options=list(
                    "auto",
                    "manual"),
                default="auto")
            private$..xAxisRangeMin <- jmvcore::OptionNumber$new(
                "xAxisRangeMin",
                xAxisRangeMin,
                default=0)
            private$..xAxisRangeMax <- jmvcore::OptionNumber$new(
                "xAxisRangeMax",
                xAxisRangeMax,
                default=10)

            self$.addOption(private$..rows)
            self$.addOption(private$..columns)
            self$.addOption(private$..facet)
            self$.addOption(private$..ignoreNA)
            self$.addOption(private$..horizontal)
            self$.addOption(private$..rotateLabels)
            self$.addOption(private$..showLabels)
            self$.addOption(private$..order)
            self$.addOption(private$..yaxis1var)
            self$.addOption(private$..singleColor)
            self$.addOption(private$..position)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..borderColor)
            self$.addOption(private$..textColor)
            self$.addOption(private$..accuracy)
            self$.addOption(private$..plotWidth)
            self$.addOption(private$..plotHeight)
            self$.addOption(private$..facetBy)
            self$.addOption(private$..facetNumber)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
            self$.addOption(private$..yAxisLabelFontSize)
            self$.addOption(private$..yAxisLabelRotation)
            self$.addOption(private$..yAxisRangeType)
            self$.addOption(private$..yAxisRangeMin)
            self$.addOption(private$..yAxisRangeMax)
            self$.addOption(private$..xAxisLabelFontSize)
            self$.addOption(private$..xAxisLabelRotation)
            self$.addOption(private$..xAxisRangeType)
            self$.addOption(private$..xAxisRangeMin)
            self$.addOption(private$..xAxisRangeMax)
        }),
    active = list(
        rows = function() private$..rows$value,
        columns = function() private$..columns$value,
        facet = function() private$..facet$value,
        ignoreNA = function() private$..ignoreNA$value,
        horizontal = function() private$..horizontal$value,
        rotateLabels = function() private$..rotateLabels$value,
        showLabels = function() private$..showLabels$value,
        order = function() private$..order$value,
        yaxis1var = function() private$..yaxis1var$value,
        singleColor = function() private$..singleColor$value,
        position = function() private$..position$value,
        colorPalette = function() private$..colorPalette$value,
        borderColor = function() private$..borderColor$value,
        textColor = function() private$..textColor$value,
        accuracy = function() private$..accuracy$value,
        plotWidth = function() private$..plotWidth$value,
        plotHeight = function() private$..plotHeight$value,
        facetBy = function() private$..facetBy$value,
        facetNumber = function() private$..facetNumber$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value,
        yAxisLabelFontSize = function() private$..yAxisLabelFontSize$value,
        yAxisLabelRotation = function() private$..yAxisLabelRotation$value,
        yAxisRangeType = function() private$..yAxisRangeType$value,
        yAxisRangeMin = function() private$..yAxisRangeMin$value,
        yAxisRangeMax = function() private$..yAxisRangeMax$value,
        xAxisLabelFontSize = function() private$..xAxisLabelFontSize$value,
        xAxisLabelRotation = function() private$..xAxisLabelRotation$value,
        xAxisRangeType = function() private$..xAxisRangeType$value,
        xAxisRangeMin = function() private$..xAxisRangeMin$value,
        xAxisRangeMax = function() private$..xAxisRangeMax$value),
    private = list(
        ..rows = NA,
        ..columns = NA,
        ..facet = NA,
        ..ignoreNA = NA,
        ..horizontal = NA,
        ..rotateLabels = NA,
        ..showLabels = NA,
        ..order = NA,
        ..yaxis1var = NA,
        ..singleColor = NA,
        ..position = NA,
        ..colorPalette = NA,
        ..borderColor = NA,
        ..textColor = NA,
        ..accuracy = NA,
        ..plotWidth = NA,
        ..plotHeight = NA,
        ..facetBy = NA,
        ..facetNumber = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA,
        ..yAxisLabelFontSize = NA,
        ..yAxisLabelRotation = NA,
        ..yAxisRangeType = NA,
        ..yAxisRangeMin = NA,
        ..yAxisRangeMax = NA,
        ..xAxisLabelFontSize = NA,
        ..xAxisLabelRotation = NA,
        ..xAxisRangeType = NA,
        ..xAxisRangeMin = NA,
        ..xAxisRangeMax = NA)
)

barplotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="",
                width=600,
                height=400,
                renderFun=".plot"))}))

barplotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "barplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "barplot",
                version = c(1,0,0),
                options = options,
                results = barplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bar Plot
#'
#' 
#' @param data .
#' @param rows .
#' @param columns .
#' @param facet .
#' @param ignoreNA .
#' @param horizontal .
#' @param rotateLabels .
#' @param showLabels .
#' @param order .
#' @param yaxis1var .
#' @param singleColor .
#' @param position .
#' @param colorPalette .
#' @param borderColor .
#' @param textColor .
#' @param accuracy .
#' @param plotWidth .
#' @param plotHeight .
#' @param facetBy .
#' @param facetNumber .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @param yAxisLabelFontSize .
#' @param yAxisLabelRotation .
#' @param yAxisRangeType .
#' @param yAxisRangeMin .
#' @param yAxisRangeMax .
#' @param xAxisLabelFontSize .
#' @param xAxisLabelRotation .
#' @param xAxisRangeType .
#' @param xAxisRangeMin .
#' @param xAxisRangeMax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
barplot <- function(
    data,
    rows,
    columns,
    facet,
    ignoreNA = TRUE,
    horizontal = FALSE,
    rotateLabels = FALSE,
    showLabels = TRUE,
    order = "none",
    yaxis1var = "count",
    singleColor = TRUE,
    position = "dodge",
    colorPalette = "jmv",
    borderColor = "none",
    textColor = "auto",
    accuracy = "0.1",
    plotWidth = 0,
    plotHeight = 0,
    facetBy = "column",
    facetNumber = 1,
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5",
    yAxisLabelFontSize = 12,
    yAxisLabelRotation = 0,
    yAxisRangeType = "auto",
    yAxisRangeMin = 0,
    yAxisRangeMax = 10,
    xAxisLabelFontSize = 12,
    xAxisLabelRotation = 0,
    xAxisRangeType = "auto",
    xAxisRangeMin = 0,
    xAxisRangeMax = 10) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("barplot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(columns)) columns <- jmvcore::resolveQuo(jmvcore::enquo(columns))
    if ( ! missing(facet)) facet <- jmvcore::resolveQuo(jmvcore::enquo(facet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(columns), columns, NULL),
            `if`( ! missing(facet), facet, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in columns) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in facet) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barplotOptions$new(
        rows = rows,
        columns = columns,
        facet = facet,
        ignoreNA = ignoreNA,
        horizontal = horizontal,
        rotateLabels = rotateLabels,
        showLabels = showLabels,
        order = order,
        yaxis1var = yaxis1var,
        singleColor = singleColor,
        position = position,
        colorPalette = colorPalette,
        borderColor = borderColor,
        textColor = textColor,
        accuracy = accuracy,
        plotWidth = plotWidth,
        plotHeight = plotHeight,
        facetBy = facetBy,
        facetNumber = facetNumber,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition,
        yAxisLabelFontSize = yAxisLabelFontSize,
        yAxisLabelRotation = yAxisLabelRotation,
        yAxisRangeType = yAxisRangeType,
        yAxisRangeMin = yAxisRangeMin,
        yAxisRangeMax = yAxisRangeMax,
        xAxisLabelFontSize = xAxisLabelFontSize,
        xAxisLabelRotation = xAxisLabelRotation,
        xAxisRangeType = xAxisRangeType,
        xAxisRangeMin = xAxisRangeMin,
        xAxisRangeMax = xAxisRangeMax)

    analysis <- barplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

