
# This file is automatically generated, you probably don't want to edit this

mrcrosstabsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrcrosstabsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mode = NULL,
            repVar = NULL,
            separator = ";",
            emptyAsNA = TRUE,
            resps = NULL,
            group = NULL,
            group2 = NULL,
            endorsed = 1,
            optionname = "Options",
            order = "decreasing",
            computedValues = "count",
            totalRow = TRUE,
            showNbOfCases = TRUE,
            overall = TRUE,
            xaxis = "xcols",
            bartype = "dodge",
            size = "medium",
            colorPalette = "jmv",
            titleText = NULL,
            titleFontFace = "bold",
            titleFontSize = "14",
            titleAlign = "0.5",
            subtitleText = NULL,
            subtitleFontFace = "plain",
            subtitleFontSize = "12",
            subtitleAlign = "0.5",
            captionText = NULL,
            captionFontFace = "italic",
            captionFontSize = "10",
            captionAlign = "1",
            legendText = NULL,
            legendFontSize = "14",
            legendPosition = "right",
            xAxisText = NULL,
            xAxisFontSize = "16",
            xAxisPosition = "0.5",
            yAxisText = NULL,
            yAxisFontSize = "16",
            yAxisPosition = "0.5", ...) {

            super$initialize(
                package="vijPlots",
                name="mrcrosstabs",
                requiresData=TRUE,
                ...)

            private$..mode <- jmvcore::OptionList$new(
                "mode",
                mode,
                options=list(
                    "morevar",
                    "onevar"))
            private$..repVar <- jmvcore::OptionVariable$new(
                "repVar",
                repVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..separator <- jmvcore::OptionString$new(
                "separator",
                separator,
                default=";")
            private$..emptyAsNA <- jmvcore::OptionBool$new(
                "emptyAsNA",
                emptyAsNA,
                default=TRUE)
            private$..resps <- jmvcore::OptionVariables$new(
                "resps",
                resps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group2 <- jmvcore::OptionVariable$new(
                "group2",
                group2,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..endorsed <- jmvcore::OptionInteger$new(
                "endorsed",
                endorsed,
                default=1)
            private$..optionname <- jmvcore::OptionString$new(
                "optionname",
                optionname,
                default="Options")
            private$..order <- jmvcore::OptionList$new(
                "order",
                order,
                options=list(
                    "decreasing",
                    "increasing",
                    "none"),
                default="decreasing")
            private$..computedValues <- jmvcore::OptionList$new(
                "computedValues",
                computedValues,
                options=list(
                    "count",
                    "responses",
                    "cases",
                    "options"),
                default="count")
            private$..totalRow <- jmvcore::OptionBool$new(
                "totalRow",
                totalRow,
                default=TRUE)
            private$..showNbOfCases <- jmvcore::OptionBool$new(
                "showNbOfCases",
                showNbOfCases,
                default=TRUE)
            private$..overall <- jmvcore::OptionBool$new(
                "overall",
                overall,
                default=TRUE)
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xcols")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")
            private$..size <- jmvcore::OptionList$new(
                "size",
                size,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "wide",
                    "huge"),
                default="medium")
            private$..colorPalette <- jmvcore::OptionList$new(
                "colorPalette",
                colorPalette,
                options=list(
                    "jmv",
                    "Set1",
                    "Set2",
                    "Set3",
                    "Pastel1",
                    "Pastel2",
                    "Accent",
                    "Paired",
                    "Dark2",
                    "Spectral",
                    "RdYlGn",
                    "RdYlBu",
                    "RdGy",
                    "RdBu",
                    "PuOr",
                    "PRGn",
                    "PiYG",
                    "BrBG",
                    "Blues",
                    "Greens",
                    "Greys",
                    "Oranges",
                    "Purples",
                    "Reds",
                    "BuGn",
                    "BuPu",
                    "GnBu",
                    "OrRd",
                    "PuBu",
                    "PuBuGn",
                    "PuRd",
                    "RdPu",
                    "YlGn",
                    "YlGnBu",
                    "YlOrBr",
                    "YlOrRd",
                    "viridis::viridis",
                    "viridis::magma",
                    "viridis::inferno",
                    "viridis::plasma",
                    "viridis::turbo",
                    "dichromat::Categorical.12"),
                default="jmv")
            private$..titleText <- jmvcore::OptionString$new(
                "titleText",
                titleText)
            private$..titleFontFace <- jmvcore::OptionList$new(
                "titleFontFace",
                titleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="bold")
            private$..titleFontSize <- jmvcore::OptionList$new(
                "titleFontSize",
                titleFontSize,
                options=list(
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22",
                    "24"),
                default="14")
            private$..titleAlign <- jmvcore::OptionList$new(
                "titleAlign",
                titleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..subtitleText <- jmvcore::OptionString$new(
                "subtitleText",
                subtitleText)
            private$..subtitleFontFace <- jmvcore::OptionList$new(
                "subtitleFontFace",
                subtitleFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="plain")
            private$..subtitleFontSize <- jmvcore::OptionList$new(
                "subtitleFontSize",
                subtitleFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20",
                    "22"),
                default="12")
            private$..subtitleAlign <- jmvcore::OptionList$new(
                "subtitleAlign",
                subtitleAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..captionText <- jmvcore::OptionString$new(
                "captionText",
                captionText)
            private$..captionFontFace <- jmvcore::OptionList$new(
                "captionFontFace",
                captionFontFace,
                options=list(
                    "plain",
                    "bold",
                    "italic",
                    "bold.italic"),
                default="italic")
            private$..captionFontSize <- jmvcore::OptionList$new(
                "captionFontSize",
                captionFontSize,
                options=list(
                    "8",
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="10")
            private$..captionAlign <- jmvcore::OptionList$new(
                "captionAlign",
                captionAlign,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="1")
            private$..legendText <- jmvcore::OptionString$new(
                "legendText",
                legendText)
            private$..legendFontSize <- jmvcore::OptionList$new(
                "legendFontSize",
                legendFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="14")
            private$..legendPosition <- jmvcore::OptionList$new(
                "legendPosition",
                legendPosition,
                options=list(
                    "right",
                    "bottom",
                    "left",
                    "top"),
                default="right")
            private$..xAxisText <- jmvcore::OptionString$new(
                "xAxisText",
                xAxisText)
            private$..xAxisFontSize <- jmvcore::OptionList$new(
                "xAxisFontSize",
                xAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..xAxisPosition <- jmvcore::OptionList$new(
                "xAxisPosition",
                xAxisPosition,
                options=list(
                    "0",
                    "0.5",
                    "1"),
                default="0.5")
            private$..yAxisText <- jmvcore::OptionString$new(
                "yAxisText",
                yAxisText)
            private$..yAxisFontSize <- jmvcore::OptionList$new(
                "yAxisFontSize",
                yAxisFontSize,
                options=list(
                    "10",
                    "12",
                    "14",
                    "16",
                    "18",
                    "20"),
                default="16")
            private$..yAxisPosition <- jmvcore::OptionList$new(
                "yAxisPosition",
                yAxisPosition,
                options=list(
                    "1",
                    "0.5",
                    "0"),
                default="0.5")

            self$.addOption(private$..mode)
            self$.addOption(private$..repVar)
            self$.addOption(private$..separator)
            self$.addOption(private$..emptyAsNA)
            self$.addOption(private$..resps)
            self$.addOption(private$..group)
            self$.addOption(private$..group2)
            self$.addOption(private$..endorsed)
            self$.addOption(private$..optionname)
            self$.addOption(private$..order)
            self$.addOption(private$..computedValues)
            self$.addOption(private$..totalRow)
            self$.addOption(private$..showNbOfCases)
            self$.addOption(private$..overall)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
            self$.addOption(private$..size)
            self$.addOption(private$..colorPalette)
            self$.addOption(private$..titleText)
            self$.addOption(private$..titleFontFace)
            self$.addOption(private$..titleFontSize)
            self$.addOption(private$..titleAlign)
            self$.addOption(private$..subtitleText)
            self$.addOption(private$..subtitleFontFace)
            self$.addOption(private$..subtitleFontSize)
            self$.addOption(private$..subtitleAlign)
            self$.addOption(private$..captionText)
            self$.addOption(private$..captionFontFace)
            self$.addOption(private$..captionFontSize)
            self$.addOption(private$..captionAlign)
            self$.addOption(private$..legendText)
            self$.addOption(private$..legendFontSize)
            self$.addOption(private$..legendPosition)
            self$.addOption(private$..xAxisText)
            self$.addOption(private$..xAxisFontSize)
            self$.addOption(private$..xAxisPosition)
            self$.addOption(private$..yAxisText)
            self$.addOption(private$..yAxisFontSize)
            self$.addOption(private$..yAxisPosition)
        }),
    active = list(
        mode = function() private$..mode$value,
        repVar = function() private$..repVar$value,
        separator = function() private$..separator$value,
        emptyAsNA = function() private$..emptyAsNA$value,
        resps = function() private$..resps$value,
        group = function() private$..group$value,
        group2 = function() private$..group2$value,
        endorsed = function() private$..endorsed$value,
        optionname = function() private$..optionname$value,
        order = function() private$..order$value,
        computedValues = function() private$..computedValues$value,
        totalRow = function() private$..totalRow$value,
        showNbOfCases = function() private$..showNbOfCases$value,
        overall = function() private$..overall$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value,
        size = function() private$..size$value,
        colorPalette = function() private$..colorPalette$value,
        titleText = function() private$..titleText$value,
        titleFontFace = function() private$..titleFontFace$value,
        titleFontSize = function() private$..titleFontSize$value,
        titleAlign = function() private$..titleAlign$value,
        subtitleText = function() private$..subtitleText$value,
        subtitleFontFace = function() private$..subtitleFontFace$value,
        subtitleFontSize = function() private$..subtitleFontSize$value,
        subtitleAlign = function() private$..subtitleAlign$value,
        captionText = function() private$..captionText$value,
        captionFontFace = function() private$..captionFontFace$value,
        captionFontSize = function() private$..captionFontSize$value,
        captionAlign = function() private$..captionAlign$value,
        legendText = function() private$..legendText$value,
        legendFontSize = function() private$..legendFontSize$value,
        legendPosition = function() private$..legendPosition$value,
        xAxisText = function() private$..xAxisText$value,
        xAxisFontSize = function() private$..xAxisFontSize$value,
        xAxisPosition = function() private$..xAxisPosition$value,
        yAxisText = function() private$..yAxisText$value,
        yAxisFontSize = function() private$..yAxisFontSize$value,
        yAxisPosition = function() private$..yAxisPosition$value),
    private = list(
        ..mode = NA,
        ..repVar = NA,
        ..separator = NA,
        ..emptyAsNA = NA,
        ..resps = NA,
        ..group = NA,
        ..group2 = NA,
        ..endorsed = NA,
        ..optionname = NA,
        ..order = NA,
        ..computedValues = NA,
        ..totalRow = NA,
        ..showNbOfCases = NA,
        ..overall = NA,
        ..xaxis = NA,
        ..bartype = NA,
        ..size = NA,
        ..colorPalette = NA,
        ..titleText = NA,
        ..titleFontFace = NA,
        ..titleFontSize = NA,
        ..titleAlign = NA,
        ..subtitleText = NA,
        ..subtitleFontFace = NA,
        ..subtitleFontSize = NA,
        ..subtitleAlign = NA,
        ..captionText = NA,
        ..captionFontFace = NA,
        ..captionFontSize = NA,
        ..captionAlign = NA,
        ..legendText = NA,
        ..legendFontSize = NA,
        ..legendPosition = NA,
        ..xAxisText = NA,
        ..xAxisFontSize = NA,
        ..xAxisPosition = NA,
        ..yAxisText = NA,
        ..yAxisFontSize = NA,
        ..yAxisPosition = NA)
)

mrcrosstabsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrcrosstabsResults",
    inherit = jmvcore::Group,
    active = list(
        helpMessage = function() private$.items[["helpMessage"]],
        crosstab = function() private$.items[["crosstab"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multiple Response Crosstab")
            self$add(jmvcore::Html$new(
                options=options,
                name="helpMessage",
                title="",
                visible=TRUE,
                content=" <style> .block { border: 2px solid gray; border-radius: 15px; background-color: WhiteSmoke; padding: 0px 20px; text-align: justify; } </style> <div class=\"block\"> <p><strong>Multiple Response Crosstab Help</strong></p>\n<p>This module computes crosstab frequencies for multiple response questions, also known as \"Check All That Apply\" (CATA) questions.</p>\n<p>Questions may be coded as : <ul> <li>several <strong>dummy (or indicator) variables</strong> using 0/1 or 1/2 for each possible answer</li> <li>a single <strong>multi-valued variable</strong> containing the checked answers, separated by a symbol (usually \",\" or \";\").</li> </ul></p>\n<p>A sample file is included at Open > Data Library > vijPlots > Credit Cards</p>\n</div>"))
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstab",
                title="Crosstab",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Options", 
                        `type`="text")),
                clearWith=list(
                    "mode",
                    "repVar",
                    "group2",
                    "separator",
                    "emptyAsNA",
                    "resps",
                    "group",
                    "endorsed",
                    "optionname",
                    "order",
                    "computedValues",
                    "showNbOfCases",
                    "totalRow",
                    "overall")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plots",
                width=400,
                height=300,
                renderFun=".plot"))}))

mrcrosstabsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mrcrosstabsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "vijPlots",
                name = "mrcrosstabs",
                version = c(1,0,0),
                options = options,
                results = mrcrosstabsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Crosstab
#'
#' 
#' @param data .
#' @param mode .
#' @param repVar .
#' @param separator .
#' @param emptyAsNA .
#' @param resps .
#' @param group .
#' @param group2 .
#' @param endorsed .
#' @param optionname .
#' @param order .
#' @param computedValues .
#' @param totalRow .
#' @param showNbOfCases .
#' @param overall .
#' @param xaxis .
#' @param bartype .
#' @param size .
#' @param colorPalette .
#' @param titleText .
#' @param titleFontFace .
#' @param titleFontSize .
#' @param titleAlign .
#' @param subtitleText .
#' @param subtitleFontFace .
#' @param subtitleFontSize .
#' @param subtitleAlign .
#' @param captionText .
#' @param captionFontFace .
#' @param captionFontSize .
#' @param captionAlign .
#' @param legendText .
#' @param legendFontSize .
#' @param legendPosition .
#' @param xAxisText .
#' @param xAxisFontSize .
#' @param xAxisPosition .
#' @param yAxisText .
#' @param yAxisFontSize .
#' @param yAxisPosition .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$helpMessage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$crosstab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstab$asDF}
#'
#' \code{as.data.frame(results$crosstab)}
#'
#' @export
mrcrosstabs <- function(
    data,
    mode,
    repVar,
    separator = ";",
    emptyAsNA = TRUE,
    resps,
    group,
    group2,
    endorsed = 1,
    optionname = "Options",
    order = "decreasing",
    computedValues = "count",
    totalRow = TRUE,
    showNbOfCases = TRUE,
    overall = TRUE,
    xaxis = "xcols",
    bartype = "dodge",
    size = "medium",
    colorPalette = "jmv",
    titleText,
    titleFontFace = "bold",
    titleFontSize = "14",
    titleAlign = "0.5",
    subtitleText,
    subtitleFontFace = "plain",
    subtitleFontSize = "12",
    subtitleAlign = "0.5",
    captionText,
    captionFontFace = "italic",
    captionFontSize = "10",
    captionAlign = "1",
    legendText,
    legendFontSize = "14",
    legendPosition = "right",
    xAxisText,
    xAxisFontSize = "16",
    xAxisPosition = "0.5",
    yAxisText,
    yAxisFontSize = "16",
    yAxisPosition = "0.5") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mrcrosstabs requires jmvcore to be installed (restart may be required)")

    if ( ! missing(repVar)) repVar <- jmvcore::resolveQuo(jmvcore::enquo(repVar))
    if ( ! missing(resps)) resps <- jmvcore::resolveQuo(jmvcore::enquo(resps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(group2)) group2 <- jmvcore::resolveQuo(jmvcore::enquo(group2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(repVar), repVar, NULL),
            `if`( ! missing(resps), resps, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(group2), group2, NULL))

    for (v in repVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in resps) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group2) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mrcrosstabsOptions$new(
        mode = mode,
        repVar = repVar,
        separator = separator,
        emptyAsNA = emptyAsNA,
        resps = resps,
        group = group,
        group2 = group2,
        endorsed = endorsed,
        optionname = optionname,
        order = order,
        computedValues = computedValues,
        totalRow = totalRow,
        showNbOfCases = showNbOfCases,
        overall = overall,
        xaxis = xaxis,
        bartype = bartype,
        size = size,
        colorPalette = colorPalette,
        titleText = titleText,
        titleFontFace = titleFontFace,
        titleFontSize = titleFontSize,
        titleAlign = titleAlign,
        subtitleText = subtitleText,
        subtitleFontFace = subtitleFontFace,
        subtitleFontSize = subtitleFontSize,
        subtitleAlign = subtitleAlign,
        captionText = captionText,
        captionFontFace = captionFontFace,
        captionFontSize = captionFontSize,
        captionAlign = captionAlign,
        legendText = legendText,
        legendFontSize = legendFontSize,
        legendPosition = legendPosition,
        xAxisText = xAxisText,
        xAxisFontSize = xAxisFontSize,
        xAxisPosition = xAxisPosition,
        yAxisText = yAxisText,
        yAxisFontSize = yAxisFontSize,
        yAxisPosition = yAxisPosition)

    analysis <- mrcrosstabsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

